#!/usr/bin/env bash

PORT=8080
ADDRESS='0.0.0.0'

fatal() {
	echo '[fatal]' "$@" >&2
	exit 1
}

enable accept || fatal 'failed to load accept'

echo "listening on http://$ADDRESS:$PORT"
accept -b "$ADDRESS" -v fd -r ip "$PORT"

while read -u "$fd" line; do
	line=${line%$'\r'}
	echo "got data: $line"

	if [[ -z $line ]]; then
		break
	fi
done

exec {fd}>&-
